// interfaces/actionTypes.ts

const actionTypes = {
  SET_PDF_LOADING: 'SET_PDF_LOADING',
  SET_PDF_ENTRIES: 'SET_PDF_ENTRIES',
  SET_PDF_ERROR: 'SET_PDF_ERROR',
  CLEAR_PDF_ENTRIES: 'CLEAR_PDF_ENTRIES',

  ADD_TOOL: 'ADD_TOOL',
  REMOVE_TOOL: 'REMOVE_TOOL',
  ADD_PROMPT: 'ADD_PROMPT',
  REMOVE_PROMPT: 'REMOVE_PROMPT',
  ADD_RESOURCE: 'ADD_RESOURCE',
  REMOVE_RESOURCE: 'REMOVE_RESOURCE',
  ADD_MESSAGE: 'ADD_MESSAGE',
  UPDATE_LAST_AGENT_MESSAGE: 'UPDATE_LAST_AGENT_MESSAGE',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  SET_SW_STATUS: 'SET_SW_STATUS',
} as const;

export default actionTypes;
